# This runs the linter (cppcheck) and
# compiles qtplaysmf.
language: cpp
compiler: gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqt4-dev libasound2-dev cppcheck
 - cd src
script:
 - cppcheck --error-exitcode=1 .
 - cd ../examples/qtplaysmf/
 - qmake -spec linux-g++ .
 - make
